### PR TITLE
Fix: Transparency on the filter reveals a rectangle behind it that shouldn't be there.

### PR DESCRIPTION
**Pull request by Xgames123**
before
image

after
image

### CODE REVIEW

**Comment by Xgames123** [comment]
What why is the build failing. I didn't even touch that part of the code

**Comment by Cloudef** [comment]
Might be a compiler update

**Comment by Cloudef** [comment]
Does non-transparent bemenu still work in wayland and X11?

**Comment by Xgames123** [comment]
I haven't tested x11 but I don't see why not.
Il test tomorrow

**Comment by Xgames123** [comment]
Tested on wayland and x11 on default config and my config with the transparency removed

**Comment by Cloudef** [comment]
Thanks

**Pull request merged**
