### PR TITLE
Add custom key support

### PR DESCRIPTION
**Pull request by SevereOverfl0w**
Implementation of #126.  Currently in draft & only implemented for
Wayland (what I primarily use).

I wanted to get some early feedback on the implementation.  I haven't
done C for many years, and I want to make sure my approach is in keeping
with how you'd like to see this done before continuing.

### CODE REVIEW

**Comment by SevereOverfl0w** [comment]
ncurses and x11 implementations added.  The ncurses one is a little bit of a hack, but supports the <esc> prefix version mentioned here: https://stackoverflow.com/a/10216459.  The 8-bit encoding currently sends other characters, I can't find information on whether this can be detected or not.  I can extend support to detect those cases, but if users expect their terminal to send certain characters on alt-X then it will not work for those cases.  Most of the extended ascii keys aren't ones you would press normally anyway though.

Where would you like this functionality to be documented?

**Comment by SevereOverfl0w** [comment]
I've extended support to include high bit by default, branch can easily be deleted if it's not suited, etc.

**Comment by Cloudef** [comment]
Looks good. If the ncurses thing works in xterm, it's good baseline to know whether it would work on other terminal usually.

**Comment by SevereOverfl0w** [comment]
xterm only works with the high bit code (by default, this can be configured in xterm).

Kitty, the other terminal I tried, sent <esc> followed by 1.

**Comment by Cloudef** [comment]
If the terminal support seems spotty. I would be fine having this feature only for the GUIs.

**Comment by SevereOverfl0w** [comment]
I think these two methods capture the two methods that exist, or at least the two major ones.

As far as I can tell, neovim works by checking these two methods (based on docs and bug reports where it was extended/fixed).

**Comment by SevereOverfl0w** [comment]
Just to clarify, are you waiting on me to remove the terminal code?

**Comment by Cloudef** [comment]
If you think it works with majority of terminal emulators. I'm fine with having the code in. I'll test and merge this later.

**Comment by SevereOverfl0w** [comment]
Great, thanks! I'm looking forward to using this on all my machines.

**Comment by Cloudef** [comment]
Sorry for the late response. I tested this with iTerm on OSX since I don't have other machine available right now. It doesn't seem to work there, but it doesn't seem to break functionality either so it's fine. I assume it will work with the more popular terminal emulators though (especially under linux) so I'm fine with this.

**Comment by SevereOverfl0w** [comment]
Apparently iterm2 doesn't do this by default https://iterm2.com/faq.html but I'm not sure what it does send by default.

Libtickit is probably the best way to get full coverage for this stuff.

**Comment by SevereOverfl0w** [comment]
Actually, it goes a step further and implements a libtickit specific solution (which neovim uses under the hood)

**Pull request merged**
