### PR TITLE
implement wayland fractional scaling

### PR DESCRIPTION
**Pull request by stacyharper**

### CODE REVIEW

**Comment by stacyharper** [comment]
With my bemenu env variable, with my colors, it looks even more blurry now that before xD I might have missed something? The change is expected to be subtil. Someone can give it a try?

**Comment by stacyharper** [comment]
> With my bemenu env variable, with my colors, it looks even more blurry now that before xD I might have missed something? The change is expected to be subtil. Someone can give it a try?

That feeling is probably cause by the fact that without fractional support, the compositor subtle downscaling add a bit of sharpness. I'm not sure but maybe we can configure Cairo to render text better.

**Comment by Cloudef** [comment]
> perhaps this is off topic here, but even with just scale=2 and one monitor, bemenu has always been blurry for me..

Does forcing scale with BEMENU_SCALE work (try X11 backend too)

**Comment by stacyharper** [comment]
rebased over the change in #380

**Comment by Cloudef** [comment]
It seems wayland handling of BEMENU_SCALE is broken then

**Comment by Cloudef** [comment]
I reverted this commit because it caused hyprland to throw error

**Pull request merged**
