### PR TITLE
path configuration - 2nd part, prevent clashing of ncurses symbol, xinerama check 

### PR DESCRIPTION
**Pull request by sleep-walker**

### CODE REVIEW

**Comment by sleep-walker** [comment]
I removed that ncurses madness, other commits makes IMHO sense

**Comment by Cloudef** [comment]
Looks good. Thanks.

**Comment by kyrias** [comment]
`CMAKE_INSTALL_LIBDIR` can, and often is, relative, which will break this implementation. This should probably use `CMAKE_INSTALL_FULL_LIBDIR` instead.

**Comment by sleep-walker** [comment]
CMAKE_INSTALL_FULL_LIBDIR works fine for me as well.

**Comment by Cloudef** [comment]
Good point, the #define should point to CMAKE_INSTALL_FULL_LIBDIR, as it does in orbment as well for plugins.

**Comment by Cloudef** [comment]
c4a55379 Thanks @kyrias

**Pull request merged**
