### PR TITLE
Add new flag --auto-select: when there is only one entry left, automaticallty select it

### PR DESCRIPTION
**Pull request by gesellkammer**
This PR fixes --accept-single, see #335

### CODE REVIEW

**Comment by Cloudef** [comment]
I think there's confusion what accept-single is supposed to do. The accept-single is supposed to return immediately if there's only one item in the list, this seems to change the behavior that accept-single returns immediately if filter out the list enough that there remains only one item.

**Comment by gesellkammer** [comment]
I thought accept single was the pendant to dmenu's "instant" patch or
rofi's auto select. If this is not the case, would you consider adding such
an option?

**Comment by Cloudef** [comment]
Yes that kind of behavior would be a new option

**Comment by gesellkammer** [comment]
Would you accept a patch which implements that functionality under the flag "--accept-single", mirroring rofi's own option?

**Comment by Cloudef** [comment]
That would break the current expected behavior of --accept-single, patch with different flag name is okay.

**Comment by Cloudef** [comment]
Optional argument for --accept-single could work too as well I guess, something like "always"

**Comment by gesellkammer** [comment]
Reverted the behaviour of --accept-single, added a new flag --auto-select

**Comment by Cloudef** [comment]
Can you also document the flag in the man page, looks good otherwise

**Comment by gesellkammer** [comment]
Thanks

**Comment by Cloudef** [comment]
Looks like we hit string length limit:
>error: string literal of length 4104 exceeds maximum length 4095 that ISO C99 compilers are required to support

**Comment by Cloudef** [comment]
Thanks

**Pull request merged**
